rawbleadmin/urls.py
from django.contrib.auth.views import LoginView
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.debug import sensitive_post_parameters
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import dashboard,refresh_contacts,refresh_products,SeeAll
from products import views as product_views
from contacts import views as contact_views
from deals import views as deal_views
from payments import views as payment_views
from servicedelivery import views as servicedelivery_views
#from payments.views import advancepayment,AdvancePaymentDelete,AdvancePaymentCreate,advancepayment_reorder,advancepayment_reorder_moveup,advancepayment_reorder_movedown

class DangerousLoginView(LoginView):
    '''A LoginView with no CSRF protection.'''

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_exempt)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            redirect_to = self.get_success_url()
            if redirect_to == self.request.path:
                raise ValueError(
                    'Redirection loop for authenticated user detected. Check that '
                    'your LOGIN_REDIRECT_URL doesn\'t point to a login page.')
            return HttpResponseRedirect(redirect_to)
        return super(LoginView, self).dispatch(request, *args, **kwargs)








urlpatterns = [
    #path('accounts/login/',DangerousLoginView.as_view(), name='login'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
        #accounts/login/ [name='login']
        #accounts/logout/ [name='logout']
        #accounts/password_change/ [name='password_change']
        #accounts/password_change/done/ [name='password_change_done']
        #accounts/password_reset/ [name='password_reset']
        #accounts/password_reset/done/ [name='password_reset_done']
        #accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
        #accounts/reset/done/ [name='password_reset_complete']
    #path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('',dashboard,name="home"),
    path('seeall',SeeAll,name="seeall"),
    path('refresh/products/',refresh_products,name="refresh_products"),
    path('refresh/contacts/',refresh_contacts,name="refresh_contacts"),
    path('refresh/purchase_orders/',servicedelivery_views.refresh_purchase_orders,name='refresh_purchase_orders'),
    #path('refresh/unpaid_bills/',payment_views.refresh_unpaid_bills,name='refresh_unpaid_bills'),
    path('refresh/sales_orders/',servicedelivery_views.refresh_sales_order,name='refresh_sales_orders'),
    path('products_listing/',product_views.FilteredProductListView.as_view(),name='products_listing'),
    path('products_listing_post/',product_views.products_listing,name='products_listing_post'),
    path('products_listing/filter',product_views.filtering_query,name='export_filtered_query'),
    path('coa_upload/<int:pk>/',product_views.CoaFileUploadView.as_view(),name='coa_upload'),
    path('product_history/sales/<int:pk>/',product_views.product_sales_history,name='product_sales_history'),
    path('product_history/purchase/<int:pk>/',product_views.product_purchase_history,name='product_purchase_history'),
    path('recent_deals/<int:pk>/',product_views.recent_deals,name='recent_deals'),

    path('make/',product_views.MakeListView.as_view(),name='make_list'),
    path('make/create',product_views.MakeCreateView.as_view(),name='make_create'),
    path('make/delete/<int:pk>',product_views.MakeDeleteView.as_view(),name='make_delete'),

    path('product_groups/',product_views.ProductGroupList,name='product_group_list'),
    path('product_groups/create/',product_views.ProductGroupCreate,name='product_group_create'),
    path('product_groups/<int:pk>/',product_views.ProductGroupDetailView.as_view(),name='product_group_detail'),
    path('product_groups/<int:pk1>/product_remove/<int:pk2>/',product_views.product_group_product_remove,name='product_group_product_remove'),
    path('product_groups/add_more_products/<int:pk1>',product_views.product_group_add_products,name='product_group_add_product'),
    path('product_groups/delete/<int:pk>/',product_views.ProductGroupDeleteView.as_view(),name='product_group_delete'),


    path('vendors_listing/',contact_views.vendors_listing,name='vendors_listing'),
    path('vendor_profile/<int:contact_id>/',contact_views.vendor_profile,name='vendor_profile'),
    
    path('buyers_listing/',contact_views.buyers_listing,name='buyers_listing'),
    path('buyer_profile/<int:contact_id>/',contact_views.buyer_profile,name='buyer_profile'),

    path('django_plotly_dash', include('django_plotly_dash.urls')),

    
    path('deals/buyer/zoho_estimates/',deal_views.zoho_estimates,name='zoho_estimates'),
    path('deals/buyer/zoho_salesorders/',deal_views.zoho_salesorders,name='zoho_salesorders'),
    path('deals/buyer/zoho_estimates/products/',deal_views.estimate_products,name='estimate_products'),
    path('deals/buyer/zoho_estimates/update/',deal_views.update_zoho_estimates,name='update_zoho_estimates'),
    path('deals/buyer/zoho_estimates/update_so',deal_views.update_so,name='update_so'),
    path('deals/buyer/zoho_estimate_inprogress/<int:pk>/',deal_views.zoho_estimate_inprogress,name='zoho_estimate_inprogress'),
    path('deals/buyer/zoho_salesorder_inprogress/<int:pk>/',deal_views.zoho_salesorder_inprogress,name='zoho_salesorder_inprogress'),
    path('deals/buyer/zoho_estimate/<int:pk>/',deal_views.zoho_estimate,name='zoho_estimate'),
    path('deals/buyer/zoho_salesorder/<int:pk>/',deal_views.zoho_salesorder,name='zoho_salesorder'),
    path('deals/buyer/sales_report/',deal_views.sales_report,name='sales_report'),
    path('deals/buyers/salesreport_mail_admin',deal_views.salesreport_mail_admin,name='salesreport_mail_admin'),
    path('ajax/sales_history',deal_views.sales_ajax,name='sales_history_ajax'),
    path('ajax/purchase_history',deal_views.purchase_ajax,name='purchase_history_ajax'),
    path('ajax/recent_deals',deal_views.recent_deals_ajax,name='recent_deals_ajax'),
    path('ajax/graph',deal_views.graph_ajax,name='graph_ajax'),
    path('ajax/coa_view',deal_views.coa_view_ajax,name='coa_view_ajax'),
    path('ajax/coa_delete/<int:pk>/',deal_views.coa_delete_ajax,name='coa_delete_ajax'),
    path('ajax/googlechartsapp',deal_views.googlechartsapp_ajax,name='googlechartsapp_ajax'),

    path('ajax/single-vendor-dealform/',deal_views.single_vendor_dealform,name='single_vendor_dealform'),
    path('ajax/vendor-deal/delete/',deal_views.vendor_deal_delete,name='vendor_deal_delete'),
    path('ajax/vendor-deal/view/',deal_views.vendor_deal_view,name='vendor_deal_view'),
    path('ajax/vendor-deal/edit/',deal_views.vendor_deal_edit,name='vendor_deal_edit'),
    path('ajax/estimate_addproduct_ajax/',deal_views.estimate_addproduct_ajax , name='estimate_addproduct_ajax'),
    path('ajax/estimate_addvendorvariation_ajax/',deal_views.estimate_addvendorvariation_ajax , name='estimate_addvendorvariation_ajax'),
    path('ajax/estimate_updatevendorvariation_ajax/',deal_views.estimate_updatevendorvariation_ajax , name='estimate_updatevendorvariation_ajax'),
    path('ajax/estimate_addvendor_ajax/',deal_views.estimate_addvendor_ajax , name='estimate_addvendor_ajax'),
    path('ajax/estimate-margin/',deal_views.estimate_margin,name="estimate_margin"),
    path('ajax/salesorder_addvendorvariation_ajax/',deal_views.salesorder_addvendorvariation_ajax , name='salesorder_addvendorvariation_ajax'),
    path('ajax/salesorder_updatevendorvariation_ajax/',deal_views.salesorder_updatevendorvariation_ajax , name='salesorder_updatevendorvariation_ajax'),
    path('ajax/salesorder_addvendor_ajax/',deal_views.salesorder_addvendor_ajax , name='salesorder_addvendor_ajax'),
    path('ajax/estimate-margin/',deal_views.estimate_margin,name="estimate_margin"),
    path('ajax/salesorder-margin/',deal_views.salesorder_margin,name="salesorder_margin"),
    path('ajax/relationship_manager_buyers/',deal_views.relationship_manager_buyers,name="relationship_manager_buyers"),
    path('ajax/purchaseorder_pickup/',servicedelivery_views.purchaseorder_pickup,name="purchaseorder_pickup"),
    path('ajax/salesorder_outward/',servicedelivery_views.salesorder_outward,name="salesorder_outward"),
    path('ajax/todays_pickup/',servicedelivery_views.todayspickup,name='todayspickup'),
    path('ajax/todays_dispatch',servicedelivery_views.todaysdispatch,name='todaysdispatch'),
    path('ajax/servicedelivery/inward/dispatchtoday',servicedelivery_views.inward_dispatchtoday,name='inward_dispatchtoday'),
    path('ajax/servicedelivery/inward/dispatchtodaysummary',servicedelivery_views.inward_dispatchtoday_summary,name='inward_dispatchtoday_summary'),
    path('ajax/servicedelivery/inward/receivingtoday',servicedelivery_views.inward_receivingtoday,name='inward_receivingtoday'),
    path('ajax/servicedelivery/inward/receivingtodaysummary',servicedelivery_views.inward_receivingtoday_summary,name='inward_receivingtoday_summary'),
    path('ajax/servicedelivery/outward/previousoutward',servicedelivery_views.previousoutward,name="previousoutward"),
    path('ajax/servicedelivery/outward/nextoutward_dispatch',servicedelivery_views.nextoutward_dispatch,name="nextoutward_dispatch"),
    path('ajax/servicedelivery/outward/nextoutward_summary',servicedelivery_views.nextoutward_summary,name="nextoutward_summary"),
    
    
    path('ajax/salesperson_stats',deal_views.salesperson_stats,name='salesperson_stats'),

products/models.py
from django.db import models
from gdstorage.storage import GoogleDriveStorage
from django.contrib.auth.models import User
# Define Google Drive Storage
gd_storage = GoogleDriveStorage()


class ProductGroup(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):

    STATUS_CHOICES = (
        ('Ac', 'active'),
        ('In', 'inactive')
    )
    group = models.ForeignKey(ProductGroup, on_delete=models.SET_NULL, blank=True, null=True, default=None)
    item_id = models.BigIntegerField(primary_key=True)
    hsn_or_sac = models.CharField(max_length=500)
    name = models.CharField(max_length=500)
    description = models.CharField(max_length=2000, blank=True)
    unit = models.CharField(max_length=50)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default='In')
    product_type = models.CharField(max_length=50)
    sku = models.CharField(max_length=500)
    make = models.CharField(max_length=100, default=" ", blank=True)
    stock_on_hand = models.IntegerField(default=0)
    zoho_location = models.CharField(max_length=200,default="okhla",null=True,blank=True)
    
    def is_active(self):
        return self.status is 'Ac'

    def __str__(self):
        return self.name

    @property
    def name_search(self):
        name_search = self.name.replace(" ", "+")
        return name_search
    
    @property
    def item_id_str(self):
        return str(self.item_id)


class CoaFile(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    file = models.FileField(upload_to='coa_files/', storage=gd_storage)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    uploaded_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.file.file.name


class Make(models.Model):

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Unit(models.Model):

    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

products/forms.py
from products.models import CoaFile, ProductGroup
from django import forms
class CoaFileForm(forms.ModelForm):
    
    class Meta:
        model = CoaFile
        fields = ("file",)

class ProductGroupForm(forms.ModelForm):

    class Meta:
        model = ProductGroup
        fields = ("name",)
        widgets = {
            'name': forms.TextInput(attrs={
                'id': 'post-text',
                'required': True,
            }),
        }

templates/products/coa_file.html
<a class="btn btn-outline-success btn-block" href="{% url "coa_upload" pk=record.item_id %}">
    <i class="fas fa-cloud-upload-alt"></i>
    Upload
</a>
<a
        href="#" class="btn {% if record.coafile_set.count > 0 %} btn-outline-info {% else %} btn-outline-dark disabled{% endif %} btn-sm btn-block coaview" role="button" data-toggle="modal" {% if record.coafile_set.count > 0 %} {% else %} aria-disabled="true"{% endif %} data-target=".coaview-{{ record.item_id }}" title="Quick View of Coa Files Uploaded" data-id="{{ record.item_id }}" class="btn btn-outline-primary btn-block" >
    {% if record.coafile_set.count > 0 %}
        <i class="fas fa-eye"></i>
    {% else %}
        <i class="fas fa-eye-slash"></i>
    {% endif %}
    View
</a>
{% if record.coafile_set.count > 0 %}
<a href="{% url "coa_upload" pk=record.item_id %}" class="btn btn-outline-danger  btn-block">
    <i class="fas fa-trash"></i>
    Delete
</a>
{% endif %}
<br>
{% if record.coafile_set.count > 0 %}
    <span style="font-weight:bold;">[ {{ record.coafile_set.count }} COAs Uploaded]</span>
{% else %}
    <span style="color:red;font-weight:bold;">No COAs Uploaded</span>
{% endif %}
<div class="modal fade coaview-{{ record.item_id }}"  tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content" style="left:-19%;width:141%">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle" style="margin-left:auto;">COA files:</h5>
                <h4 style="text-align:center;">
                    <span style="text-decoration: underline;">{{ record.name }} </span>
                </h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>'

templates/products/make_confirm_delete.html
{% extends 'home.html' %}

{% block application-active %}
<h1 style="text-align: center;margin-top:5%;"><span style="text-decoration: underline;"><strong>Delete Make  :  {{ make.name }}</strong></span></h1>
<p style="text-align: center;">&nbsp;</p>
<form method="post">{% csrf_token %}
    <p style="text-align:center">Are you sure you want to delete "{{ make.name  }}"?</p>
    <input type="submit" value="Confirm" style="margin-bottom: 5%;
    margin-left: auto;
    margin-right: auto;
    display: block;">
</form>
{% endblock application-active %}

templates/products/make_form.html
{% extends 'home.html' %}
{% load crispy_forms_tags %}

{% block application-active %}

<h1 style="text-align: center;margin-top:5%;"><span style="text-decoration: underline;"><strong>Create New MAKE</strong></span></h1>
<p style="text-align: center;">&nbsp;</p>
<form method="post">
{% csrf_token %}
    {{ form.name |as_crispy_field}}
    <input type="submit" value="Save" style="    margin-bottom: 5%;
    display: block;
    
    margin-left: auto;
    margin-right: auto;">
</form>

{% endblock application-active %}

templates/products/make_list.html
{% extends 'home.html' %}

{% block application-active %}
<h1 style="text-align: center;margin-top:5%;"><span style="text-decoration: underline;"><strong>List Of MAKE</strong></span></h1>
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;"><strong><a href="{% url 'make_create' %}">Add New MAKE </a></strong></p>
<p style="text-align: center;">&nbsp;</p>


{% if make_list %}
<div class="container" style="margin-top:4%;margin-bottom:4%">
<table id="example" class="table table-striped table-bordered " style="width:100%">
        <thead>
            <tr>
                <th>Make</th>
                <th>-------</th>
                <th>-------</th>
                <th>-------</th>
                <th>-------</th>
                <th>Delete</th>
                
            </tr>
        </thead>
        <tbody>
            {% for make in make_list%}
            <tr>
                <td>{{ make.name }}</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><a href="{% url 'make_delete' pk=make.pk %}">Delete Make</a></td>
               
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <th>Group Name</th>
                <th>-------</th>
                <th>-------</th>
                <th>-------</th>
                <th>-------</th>
                <th>Delete</th>
                
            </tr>
        </tfoot>
    </table>
</div>
{% else %}
<h2> No Groups Created </h2>
{% endif %}

{% endblock application-active %}

templates/products/productgroup_detail.html
{% extends 'home.html' %}
{% block page-title-var %} Group Detail {% endblock page-title-var %}
{% block application-active %}

<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;color: black;
    font-weight: 500;"><strong>Group Name</strong> : {{ productgroup.name }}</p>
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;">&nbsp;</p>

<table class="table table-hover" style="margin-bottom:5%">
  <thead>
    <tr>
      <th scope="col" style="text-decoration:underline">Product Name</th>
      <th scope="col">---</th>
      <th scope="col">Stock On Hand</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  {% for product  in productgroup.product_set.all %}
  <tbody>
    <tr>
      <th scope="row">{{ product.name }} </th>
      <td>---</td>
      <td>{{ product.stock_on_hand }}</td>
      <td><a class="btn btn-outline-primary btn-sm" href="{% url 'product_group_product_remove' pk1=productgroup.id pk2=product.pk %}">REMOVE</a></td>
    </tr>
  {% endfor %}

  </tbody>
</table>

<a class="btn btn-outline-primary btn-lg" href="{% url 'product_group_add_product' pk1=productgroup.id %}" style="display:block;text-align:center;font-weight:900;margin-bottom:5%;"> Add More Products </a>

{% endblock application-active %}

templates/products/productgroup_form.html
{% extends 'home.html' %}
{% load crispy_forms_tags %}
{% block page-title-var %} Create New Product Group {% endblock page-title-var %}
{% block application-active %}

<p style="text-align: center;">&nbsp;</p>
<form method="post">
{% csrf_token %}
    {{ form.name |as_crispy_field}}
    <input type="submit" value="Save" style="    margin-bottom: 5%;
    display: block;
    
    margin-left: auto;
    margin-right: auto;">
</form>

{% endblock application-active %}

templates/products/products_listing.html
{% extends 'home.html' %}

{% block page-title-var %} Products List {% endblock page-title-var %}


{% block application-active %}


<div class="container" style="margin-top:4%;margin-bottom:4%">
<table id="example" class="table table-striped table-bordered " style="width:100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Status</th>
                <th>Stock On Hand</th>
                <th>Unit</th>
                <th>Group Name</th>
                <th>info</th>
                <th>Coa Files</th>
                
                 

            </tr>
        </thead>
        <tbody>
            {% for product in product_list%}
            <tr>
                <td>{{ product.name }}</td>
                <td> {% if product.status == 'Ac'%} Active {% else %} In-Active {% endif %}</td>
                <td>{{ product.stock_on_hand }} </td>
                <td>  {{ product.unit }}  </td>
                <td>{{ product.group }}</td>
                <td>
                  <a href="#" class="btn btn-outline-primary btn-sm btn-block sales_history" data-toggle="modal" data-target=".sales-{{ product.pk }}" data-id='{{ product.pk }}' title="Sales History(Zoho Books Invoice)">Sales</a>
                  <a href="#" class="btn btn-outline-primary btn-sm btn-block purchase_history" data-toggle="modal" data-target=".purchase-{{ product.pk }}" data-id='{{ product.pk }}' title="Purchase History(Zoho Books Bills)">Purchase</a>
                  
                  <a href="#" class="btn btn-outline-primary btn-sm btn-block recent_deals {% if product.dealvendor_set.all %} disabled {% endif %}" {% if product.dealvendor_set.all %} aria-disabled="true" {% endif %} data-toggle="modal" data-target=".recent-{{ product.pk }}" data-id='{{ product.pk }}' title="Recent Vendor Deals">Recent Deals</a>
                  
                  <a href="#" class="btn btn-outline-primary btn-sm btn-block graph" data-toggle="modal" data-target=".graph-{{ product.pk }}" title="Detailed Summary Vendor Wise" data-id='{{ product.pk }}'><i class="fas fa-chart-area"></i> Summary</a>
                  <a href="#" class="btn btn-outline-primary btn-sm btn-block googlechartsapp" data-toggle="modal" data-target=".googlechartsapp-{{ product.pk }}" title="Google Charts To Filter Data" data-id='{{ product.pk }}'><i class="fas fa-chart-area"></i>Google Charts App</a>
                
                </td>
                <td>
                  <a class="btn btn-outline-primary btn-block" href="{% url 'coa_upload' pk=product.pk %}">Upload</a>
                  <a  href="#" class="btn btn-outline-primary btn-sm btn-block coaview" data-toggle="modal" data-target=".coaview-{{ product.pk }}" title="Quick View of Coa Files Uploaded" data-id='{{ product.pk }}' class="btn btn-outline-primary btn-block" >View</a>
              
              <div class="modal fade coaview-{{ product.pk }}"  tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content" style="left:-19%;width:141%">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle" style="margin-left:auto;">COA files:</h5><h4 style="text-align:center;"><span style="text-decoration: underline;">{{ product.name }} </span> </h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                  
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    
                  </div>
                </div>
              </div>
            </div>
                </td>
                
                    
            
            
            
            


            <!-- MODALS -->
            <!-- SALES MODAL -->
            <div class="modal fade sales-{{ product.pk }}"  tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle" style="margin-left:auto;">Sales of :</h5>
                    <h4 style="text-align:center;"><span style="text-decoration: underline;"> {{ product.name }} </span></h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                  
                    
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    
                  </div>
                </div>
              </div>
            </div>
            <!-- PURCHASES MODAL -->
            <div class="modal fade purchase-{{ product.pk }}"  tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle" style="margin-left:auto;">Purchases of:</h5><h4 style="text-align:center;"><span style="text-decoration: underline;"> {{ product.name }} </span></h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                  
                    
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    
                  </div>
                </div>
              </div>
            </div>

            <!-- RECENT VENDOR DEALS MODAL -->
            <div class="modal fade recent-{{ product.pk }}"  tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content" style="left:-19%;width:141%">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle" style="margin-left:auto;">Recent Vendor Deals of:</h5><h4 style="text-align:center;"><span style="text-decoration: underline;">{{ product.name }} </span> </h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                  
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    
                  </div>
                </div>
              </div>
            </div>
            <!-- Graphical Summary MODAL -->
            <div class="modal fade graph-{{ product.pk }}"  tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content" style="left:-19%;width:141%">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle" style="margin-left:auto;">Summary</h5><h4 style="text-align:center;"><span style="text-decoration: underline;">{{ product.name }} </span> </h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                  
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    
                  </div>
                </div>
              </div>
            </div>
            <!-- Google Charts App MODAL -->
            <div class="modal fade googlechartsapp-{{ product.pk }}"  tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content" style="left:-35%;width:170%">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle" style="margin-left:auto;">GOOGLE CHARTS</h5><h4 style="text-align:center;"><span style="text-decoration: underline;">{{ product.name }} </span> </h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                  
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    
                  </div>
                </div>
              </div>
            </div>
           
                
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <th>Name</th>
                <th>Status</th>
                <th>Stock On Hand</th>
                <th>Unit</th>
                <th>Group Name</th>
                <th></th>
            </tr>
        </tfoot>
    </table>
    </div>

{% endblock application-active %}