rawbleadmin/urls.py
from django.contrib.auth.views import LoginView
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.debug import sensitive_post_parameters
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import dashboard,refresh_contacts,refresh_products,SeeAll
from products import views as product_views
from contacts import views as contact_views
from deals import views as deal_views
from payments import views as payment_views
from servicedelivery import views as servicedelivery_views
#from payments.views import advancepayment,AdvancePaymentDelete,AdvancePaymentCreate,advancepayment_reorder,advancepayment_reorder_moveup,advancepayment_reorder_movedown

class DangerousLoginView(LoginView):
    '''A LoginView with no CSRF protection.'''

    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_exempt)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            redirect_to = self.get_success_url()
            if redirect_to == self.request.path:
                raise ValueError(
                    'Redirection loop for authenticated user detected. Check that '
                    'your LOGIN_REDIRECT_URL doesn\'t point to a login page.')
            return HttpResponseRedirect(redirect_to)
        return super(LoginView, self).dispatch(request, *args, **kwargs)








urlpatterns = [
    #path('accounts/login/',DangerousLoginView.as_view(), name='login'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
        #accounts/login/ [name='login']
        #accounts/logout/ [name='logout']
        #accounts/password_change/ [name='password_change']
        #accounts/password_change/done/ [name='password_change_done']
        #accounts/password_reset/ [name='password_reset']
        #accounts/password_reset/done/ [name='password_reset_done']
        #accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
        #accounts/reset/done/ [name='password_reset_complete']
    #path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('',dashboard,name="home"),
    path('seeall',SeeAll,name="seeall"),
    path('refresh/products/',refresh_products,name="refresh_products"),
    path('refresh/contacts/',refresh_contacts,name="refresh_contacts"),
    path('refresh/purchase_orders/',servicedelivery_views.refresh_purchase_orders,name='refresh_purchase_orders'),
    #path('refresh/unpaid_bills/',payment_views.refresh_unpaid_bills,name='refresh_unpaid_bills'),
    path('refresh/sales_orders/',servicedelivery_views.refresh_sales_order,name='refresh_sales_orders'),
    path('products_listing/',product_views.FilteredProductListView.as_view(),name='products_listing'),
    path('products_listing_post/',product_views.products_listing,name='products_listing_post'),
    path('products_listing/filter',product_views.filtering_query,name='export_filtered_query'),
    path('coa_upload/<int:pk>/',product_views.CoaFileUploadView.as_view(),name='coa_upload'),
    path('product_history/sales/<int:pk>/',product_views.product_sales_history,name='product_sales_history'),
    path('product_history/purchase/<int:pk>/',product_views.product_purchase_history,name='product_purchase_history'),
    path('recent_deals/<int:pk>/',product_views.recent_deals,name='recent_deals'),

    path('make/',product_views.MakeListView.as_view(),name='make_list'),
    path('make/create',product_views.MakeCreateView.as_view(),name='make_create'),
    path('make/delete/<int:pk>',product_views.MakeDeleteView.as_view(),name='make_delete'),

    path('product_groups/',product_views.ProductGroupList,name='product_group_list'),
    path('product_groups/create/',product_views.ProductGroupCreate,name='product_group_create'),
    path('product_groups/<int:pk>/',product_views.ProductGroupDetailView.as_view(),name='product_group_detail'),
    path('product_groups/<int:pk1>/product_remove/<int:pk2>/',product_views.product_group_product_remove,name='product_group_product_remove'),
    path('product_groups/add_more_products/<int:pk1>',product_views.product_group_add_products,name='product_group_add_product'),
    path('product_groups/delete/<int:pk>/',product_views.ProductGroupDeleteView.as_view(),name='product_group_delete'),


    path('vendors_listing/',contact_views.vendors_listing,name='vendors_listing'),
    path('vendor_profile/<int:contact_id>/',contact_views.vendor_profile,name='vendor_profile'),
    
    path('buyers_listing/',contact_views.buyers_listing,name='buyers_listing'),
    path('buyer_profile/<int:contact_id>/',contact_views.buyer_profile,name='buyer_profile'),

    path('django_plotly_dash', include('django_plotly_dash.urls')),

    
    path('deals/buyer/zoho_estimates/',deal_views.zoho_estimates,name='zoho_estimates'),
    path('deals/buyer/zoho_salesorders/',deal_views.zoho_salesorders,name='zoho_salesorders'),
    path('deals/buyer/zoho_estimates/products/',deal_views.estimate_products,name='estimate_products'),
    path('deals/buyer/zoho_estimates/update/',deal_views.update_zoho_estimates,name='update_zoho_estimates'),
    path('deals/buyer/zoho_estimates/update_so',deal_views.update_so,name='update_so'),
    path('deals/buyer/zoho_estimate_inprogress/<int:pk>/',deal_views.zoho_estimate_inprogress,name='zoho_estimate_inprogress'),
    path('deals/buyer/zoho_salesorder_inprogress/<int:pk>/',deal_views.zoho_salesorder_inprogress,name='zoho_salesorder_inprogress'),
    path('deals/buyer/zoho_estimate/<int:pk>/',deal_views.zoho_estimate,name='zoho_estimate'),
    path('deals/buyer/zoho_salesorder/<int:pk>/',deal_views.zoho_salesorder,name='zoho_salesorder'),
    path('deals/buyer/sales_report/',deal_views.sales_report,name='sales_report'),
    path('deals/buyers/salesreport_mail_admin',deal_views.salesreport_mail_admin,name='salesreport_mail_admin'),
    path('ajax/sales_history',deal_views.sales_ajax,name='sales_history_ajax'),
    path('ajax/purchase_history',deal_views.purchase_ajax,name='purchase_history_ajax'),
    path('ajax/recent_deals',deal_views.recent_deals_ajax,name='recent_deals_ajax'),
    path('ajax/graph',deal_views.graph_ajax,name='graph_ajax'),
    path('ajax/coa_view',deal_views.coa_view_ajax,name='coa_view_ajax'),
    path('ajax/coa_delete/<int:pk>/',deal_views.coa_delete_ajax,name='coa_delete_ajax'),
    path('ajax/googlechartsapp',deal_views.googlechartsapp_ajax,name='googlechartsapp_ajax'),

    path('ajax/single-vendor-dealform/',deal_views.single_vendor_dealform,name='single_vendor_dealform'),
    path('ajax/vendor-deal/delete/',deal_views.vendor_deal_delete,name='vendor_deal_delete'),
    path('ajax/vendor-deal/view/',deal_views.vendor_deal_view,name='vendor_deal_view'),
    path('ajax/vendor-deal/edit/',deal_views.vendor_deal_edit,name='vendor_deal_edit'),
    path('ajax/estimate_addproduct_ajax/',deal_views.estimate_addproduct_ajax , name='estimate_addproduct_ajax'),
    path('ajax/estimate_addvendorvariation_ajax/',deal_views.estimate_addvendorvariation_ajax , name='estimate_addvendorvariation_ajax'),
    path('ajax/estimate_updatevendorvariation_ajax/',deal_views.estimate_updatevendorvariation_ajax , name='estimate_updatevendorvariation_ajax'),
    path('ajax/estimate_addvendor_ajax/',deal_views.estimate_addvendor_ajax , name='estimate_addvendor_ajax'),
    path('ajax/estimate-margin/',deal_views.estimate_margin,name="estimate_margin"),
    path('ajax/salesorder_addvendorvariation_ajax/',deal_views.salesorder_addvendorvariation_ajax , name='salesorder_addvendorvariation_ajax'),
    path('ajax/salesorder_updatevendorvariation_ajax/',deal_views.salesorder_updatevendorvariation_ajax , name='salesorder_updatevendorvariation_ajax'),
    path('ajax/salesorder_addvendor_ajax/',deal_views.salesorder_addvendor_ajax , name='salesorder_addvendor_ajax'),
    path('ajax/estimate-margin/',deal_views.estimate_margin,name="estimate_margin"),
    path('ajax/salesorder-margin/',deal_views.salesorder_margin,name="salesorder_margin"),
    path('ajax/relationship_manager_buyers/',deal_views.relationship_manager_buyers,name="relationship_manager_buyers"),
    path('ajax/purchaseorder_pickup/',servicedelivery_views.purchaseorder_pickup,name="purchaseorder_pickup"),
    path('ajax/salesorder_outward/',servicedelivery_views.salesorder_outward,name="salesorder_outward"),
    path('ajax/todays_pickup/',servicedelivery_views.todayspickup,name='todayspickup'),
    path('ajax/todays_dispatch',servicedelivery_views.todaysdispatch,name='todaysdispatch'),
    path('ajax/servicedelivery/inward/dispatchtoday',servicedelivery_views.inward_dispatchtoday,name='inward_dispatchtoday'),
    path('ajax/servicedelivery/inward/dispatchtodaysummary',servicedelivery_views.inward_dispatchtoday_summary,name='inward_dispatchtoday_summary'),
    path('ajax/servicedelivery/inward/receivingtoday',servicedelivery_views.inward_receivingtoday,name='inward_receivingtoday'),
    path('ajax/servicedelivery/inward/receivingtodaysummary',servicedelivery_views.inward_receivingtoday_summary,name='inward_receivingtoday_summary'),
    path('ajax/servicedelivery/outward/previousoutward',servicedelivery_views.previousoutward,name="previousoutward"),
    path('ajax/servicedelivery/outward/nextoutward_dispatch',servicedelivery_views.nextoutward_dispatch,name="nextoutward_dispatch"),
    path('ajax/servicedelivery/outward/nextoutward_summary',servicedelivery_views.nextoutward_summary,name="nextoutward_summary"),
    
    
    path('ajax/salesperson_stats',deal_views.salesperson_stats,name='salesperson_stats'),

payments/models.py
from django.db import models
from ordered_model.models import OrderedModel
from contacts.models import ContactVendor
import datetime
from contacts.models import ContactVendor

class PaymentPayable(models.Model):
    
    mode = models.CharField(max_length=200,null=True,blank=True)
    vendor = models.ForeignKey(ContactVendor, on_delete = models.SET_NULL,null=True,blank=True)

class ChequePayable(models.Model):
    paymentpayable = models.ForeignKey(PaymentPayable,on_delete = models.CASCADE)
    cheque_no = models.CharField(max_length=200,null=True,blank=True)
    date = models.DateField(null=True,default=None,blank=True)
    amount = models.FloatField()
    approved_date = models.DateField(null=True,default=None,blank=True)
    signed_date = models.DateField(null=True,default=None,blank=True)
    cleared_date = models.DateField(null=True,default=None,blank=True)
    
    def __str__(self):
        return str(self.paymentpayable.vendor.contact_name)+" "+str(self.cheque_no)
    @property
    def status(self):
        if self.cleared_date:
            return "cleared"
        elif self.signed_date:
            return "signed"
        elif self.approved_date:
            return "approved"
        else:
            return "scheduled"
    

servicedelivery/models.py
from django.db import models
from deals.models import SalesOrderProduct,PurchaseOrderProduct
from products.models import CoaFile
from payments.models import PaymentPayable
#from payments.models import PaymentPayable
# Create your models here. 
class Transporter(models.Model):
    name = models.CharField(max_length=400,blank=True,null=True)
    address = models.CharField(max_length=400,blank=True,null=True)
    contact_person = models.CharField(max_length=400,blank=True,null=True)
    phone_number = models.CharField(max_length=400,blank=True,null=True)
    website_url = models.CharField(max_length=400,blank=True,null=True)
    def __str__(self):
        return self.name

class PurchaseOrderProductPlan(models.Model):
    purchaseorderproduct = models.ForeignKey(PurchaseOrderProduct,on_delete=models.CASCADE)
    planned_dispatch_date_time = models.DateTimeField(null=True,blank=True)
    planned_receive_date_time = models.DateTimeField(null=True,blank=True)
    dispatched_date_time = models.DateTimeField(null=True,blank=True)
    received_date_time = models.DateTimeField(null=True,blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    planned_quantity = models.FloatField()
    freight = models.FloatField()
    transporter = models.ForeignKey(Transporter,on_delete=models.SET_NULL,null=True,blank=True)
    dispatch_delay_reason = models.CharField(max_length = 500 , null=True, blank=True)
    receive_delay_reason = models.CharField(max_length = 500 , null=True, blank=True)
    #paymentpayable = models.ForeignKey(PaymentPayable,on_delete=models.SET_NULL)
    paymentpayable = models.ForeignKey(PaymentPayable,on_delete=models.SET_NULL,null=True,default=None)
    def __str__(self):
        return (self.purchaseorderproduct.purchaseorder.purchaseorder_number + "-" + self.purchaseorderproduct.product.name + "-"+str(self.planned_quantity))
    
    @property
    def total_amount_with_tax(self):
        return (self.total_amount_without_tax + self.tax_amount )
    @property
    def tax_amount(self):
        return (self.total_amount_without_tax * self.purchaseorderproduct.tax_percentage * 0.01)
    @property
    def total_amount_without_tax(self):
        return (self.purchaseorderproduct.purchase_price * self.planned_quantity)
    @property
    def plan_status(self):
        if(self.received_date_time):
            return "received"
        elif(self.dispatched_date_time):
            return "in-transit"
        elif(self.planned_dispatch_date_time):
            return "planned"
        else:
            return "unplanned"
    
class SalesOrderProductPlan(models.Model):
    salesorderproduct = models.ForeignKey(SalesOrderProduct,on_delete=models.CASCADE)
    planned_date_time = models.DateTimeField(null=True,blank=True)
    shipped_date_time = models.DateTimeField(null=True,blank=True)
    delivered_date_time = models.DateTimeField(null=True,blank=True)
    planned_quantity = models.FloatField()
    tracking_number = models.CharField(max_length=300,null=True,blank=True)
    transporter = models.ForeignKey(Transporter,on_delete=models.SET_NULL,null=True,blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    freight = models.FloatField()
    created_at = models.DateTimeField(auto_now_add = True)
    reschedule_reason = models.CharField(max_length = 500 , null=True, blank=True)
    tracking_status = models.CharField(max_length=300 ,null=True,blank=True )
    lr_mailsent_status= models.BooleanField(default=False)
    eta = models.DateTimeField(null=True,blank=True,default=None)
    coafile = models.ForeignKey(CoaFile,on_delete=models.SET_NULL,null=True,blank=True,default=None)
    def __str__(self):
        return (self.salesorderproduct.salesorder.salesorder_number + "-" + self.salesorderproduct.product.name + "-" +str(self.planned_quantity))
    @property
    def total_amount(self):
        return (self.salesorderproduct.so_selling_price * self.planned_quantity )
    @property
    def plan_status(self):
        if(self.delivered_date_time):
            return "delivered"
        elif(self.shipped_date_time):
            return "in-transit"
        elif(self.planned_date_time):
            return "planned"
        else:
            return "un-planned"

templates/payments/helper_ajax/actualledger.html
Outstanding Payable: {{ vendor.outstanding_payable }}

templates/payments/helper_ajax/allcheques.html
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Cheque Number</th>
      <th scope="col">Date</th>
      <th scope="col">Amount</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
  {% for cp in cps %}
    <tr>
      <th scope="row">{{ cp.cheque_no}}</th>
      <td>{{ cp.date }}</td>
      <td>{{ cp.amount }}</td>
      <td>{{ cp.status }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

templates/payments/helper_ajax/chequeledger.html
<table class="table table-bordered">
<tr>
<th class="table-secondary">Not Approved</th>
<td>{{ not_approved }}</td>
</tr>
<tr>
<th class="table-secondary">Not Signed</th>
<td>{{ not_signed }}</td>
</tr>
<tr>
<th class="table-secondary">Not Cleared</th>
<td>{{ not_cleared}}</td>
</tr>
</table>

templates/payments/helper_ajax/get_purchaseorders.html
{% for po in pos %}
<div id="accordion" role="tablist" aria-multiselectable="true">
    <div class="card mt-4">
        <h5 class="card-header" role="tab" id="headingOne">
            <a data-toggle="collapse" data-parent="#accordion" href="#po-{{ po.purchaseorder_id }}"  class="d-block">
                <i class="fa fa-chevron-down pull-right"></i> {{ po.purchaseorder_number }} 
            </a>
        </h5>

        <div id="po-{{ po.purchaseorder_id }}" class="collapse select-po" role="tabpanel" aria-labelledby="headingOne">
            <div class="card-body">
                {% if po.purchaseorderproduct_set.all %}
                <table class="table table-bordered">
                    <thead class="thead-light">
                      <tr>
                        <th></th>
                        <th scope="col">Product</th>
                        <th scope="col">Make</th>
                        <th scope="col">Quantity Ordered</th>
                        <th scope="col">Quantity Planned</th>
                        <th scope="col">Inward Status</th>
                        <th scope="col">ETA</th>
                        <th scope="col">Total Amount(without Tax)</th>
                        <th scope="col">Total Amount(with Tax)</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for pop in po.purchaseorderproduct_set.all %}
                    {% for popp in pop.purchaseorderproductplan_set.all %}
                      <tr class="{% if popp.paymentpayable %}table-danger {% else %} {% endif %}">
                        <th scope="row" id="selected"><input name="selected_popp_id" value="{{ popp.id }}" type="checkbox"{% if popp.paymentpayable %} disabled{% else %} {% endif %}></th>
                        <td>{{ popp.purchaseorderproduct.product.name }}</td>
                        <td>{{ popp.purchaseorderproduct.product.make }}</td>
                        <td>{{ popp.purchaseorderproduct.quantity }} ({{ pop.product.unit }})</td>
                        <td>{{ popp.planned_quantity }}</td>
                        <td class="{% if popp.plan_status == 'planned' %}table-danger{% elif popp.plan_status == 'in-transit' %}table-warning{% else %}table-success{% endif %}">{{ popp.plan_status }}</td>
                        <td>
                            {{ popp.planned_receive_date_time }}
                        </td>
                        <td>{{ popp.total_amount_without_tax}}</td>
                        <td>{{ popp.total_amount_with_tax}}</td>
                      </tr>

                    {% endfor %}
                    {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <p class="text-center"> Not Yet Planned </p>
                {% endif %}
            </div>
        </div>
    </div>
    
</div>


{% endfor %}

templates/payments/helper_ajax/inwarddetail.html
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Status</th>
      <th scope="col">PO #</th>
      <th scope="col">Vendor</th>
      <th scope="col">Product</th>
      <th scope="col">Quantity Ordered</th>
      <th scope="col">Quantity Planned</th>
      <th scope="col">Transporter</th>
      <th scope="col">Purchase Price</th>
    </tr>
  </thead>
  <tbody>
    {% for popp in pp.purchaseorderproductplan_set.all %}
    <tr>
        <th scope="row" class="{% if popp.plan_status == 'planned' %} table-danger {% elif popp.plan_status == 'in-transit' %} table-warning {% else %} table-success {% endif %}">{% if popp.plan_status == 'planned' %} Not Yet Dispatched {% elif popp.plan_status == 'in-transit' %} In Transit [Dispatched] {% else %} Received {% endif %}</th>
        <td>{{ popp.purchaseorderproduct.purchaseorder.purchaseorder_number }}</td>
        <td>{{ popp.purchaseorderproduct.purchaseorder.vendor.contact_name }}</td>
        <td>{{ popp.purchaseorderproduct.product.name }}</td>
        <td>{{ popp.purchaseorderproduct.quantity }}</td>
        <td>{{ popp.planned_quantity }}</td>
        <td>{{ popp.transporter.name }}</td>
        <td>{{ popp.purchaseorderproduct.purchase_price }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

templates/payments/helper_ajax/schedule_payment.html
{% csrf_token %}
<table class="table table-bordered table-sm">
    <tr>
    <th class="table-secondary">Vendor</th><th>{{ vendor.contact_name }}<input value="{{ vendor.contact_id }}" name="vendor_id" type="hidden"></th>
    <th class="table-secondary">Payment Terms</th><th>{{ vendor.payment_terms }}</th>
    </tr>
    <tr>
    <th class="table-secondary">Purchase Orders</th><th>{% for po in pos %}{{ po }} ,{% endfor %}</th>
    <th class="table-secondary">Total Amount(With Tax)</th><th>{{ total_amount }}<input type="hidden" name="total_amount" value ="{{ total_amount }}"></th>
    </tr>
    {% for popp in popps %}
        <input value="{{ popp.id }}" type="hidden" name="popp_id">
    {% endfor %}
    <tr>
    <th class="table-secondary">Number of cheques</th>
    <th>
        <select class="form-control" onchange="return each_cheque_amount(this);" id="no_of_cheque" name="no_of_cheque">
            <option value="1" data-total_amount="{{ total_amount }}">1</option>
            <option value="2" data-total_amount="{{ total_amount }}">2</option>
            <option value="3" data-total_amount="{{ total_amount }}">3</option>
            <option value="4" data-total_amount="{{ total_amount }}">4</option>
            <option value="5" data-total_amount="{{ total_amount }}">5</option>
            <option value="6" data-total_amount="{{ total_amount }}">6</option>
            <option value="7" data-total_amount="{{ total_amount }}">7</option>
            <option value="8" data-total_amount="{{ total_amount }}">8</option>
            <option value="9" data-total_amount="{{ total_amount }}">9</option>
            <option value="10" data-total_amount="{{ total_amount }}">10</option>
        </select>
    </th>
    <th class="table-secondary">Per Cheque Amount</th><th id="cheque_amount">{{ total_amount }}</th>
    </tr>

    
</table>
<div class="alert alert-danger">
<h5 class="alert-heading text-center">Schedule Dates</h5>
<p class="text-center" style="color:black;">{% for schedule_date in schedule_dates %} {{ schedule_date|date:"d-M-Y" }} , {% endfor %}</p>
</div>
<div class="alert alert-dark" id="cheques">
    <table class="table table-bordered ">
        <thead>
            <tr>
                <th>#</th>
                <th>Amount</th>
                <th>Enter Cheque Unique Number</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>#1</th>
                <th>{{ total_amount }}<input type="hidden" value="{{ total_amount }}" name="cheque_amount"></th>
                <th><input class="form-control" type="text" name="cheque_no"></th>
                <th><input class="form-control" type="date" name="cheque_date"></th>
            </tr>
        </tbody>
    </table>
</div>